name: Docker Image CI with Snyk

on:
  push:
    branches: ["main"]
  workflow_dispatch:
#   pull_request:
#     branches: [ "main" ]

env:
  IMAGE_TAG: app-snyk:v0.0.1
  GITHUB_REGISTRY: ghcr.io

jobs:
  build-scan-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and export to Docker
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          load: true
          tags: ${{ env.IMAGE_TAG }}
          cache-from: type=registry,ref=${{ env.GITHUB_REGISTRY }}/${{ github.actor }}/${{ github.repository }}/${{ env.IMAGE_TAG }}${{ env.GITHUB_REGISTRY }}/${{ github.actor }}/${{ github.repository }}/${{ env.IMAGE_TAG }}
          cache-to: type=inline

      - name: Run Snyk to check Docker image for vulnerabilities
        continue-on-error: false
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: ${{ env.IMAGE_TAG }}
          # snyk scan will fail only if critical vulnerability is found
          args: --file=Dockerfile --sarif-file-output=snyk.sarif --severity-threshold=critical --fail-on=all

      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          platforms: linux/arm64,linux/amd64
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.GITHUB_REGISTRY }}/${{ github.actor }}/${{ github.repository }}/${{ env.IMAGE_TAG }}
          cache-from: type=registry,ref=${{ env.GITHUB_REGISTRY }}/${{ github.actor }}/${{ github.repository }}/${{ env.IMAGE_TAG }}
          cache-to: type=inline
